/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domeni.Korisnik;
import domeni.Poruka;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import komunikacija.Komunikacija;
import model.ModelTabeleKlijent;

/**
 *
 * @author Korisnik
 */
public class KlijentskaForma extends javax.swing.JFrame {

    /**
     * Creates new form KlijentskaForma
     */
    Korisnik k;
    public KlijentskaForma(Korisnik k) {
        initComponents();
        setLocationRelativeTo(null);
        this.k = k;
        txtDobrodoslica.setText("zdravo "+ k.getUsername());
        txtTvojePoruke.setEditable(false);
        tblPoslednjeTri.setModel(new ModelTabeleKlijent());
        tblSveOstale.setModel(new ModelTabeleKlijent());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDobrodoslica = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cmbKorisnici = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNapisiPoruku = new javax.swing.JTextArea();
        porukaPrivatna = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTvojePoruke = new javax.swing.JTextArea();
        porukaSvima = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPoslednjeTri = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSveOstale = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCelaPoruka = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cmbKorisnici.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("aktivni korisnici:");

        jLabel2.setText("napisi poruku:");

        txtNapisiPoruku.setColumns(20);
        txtNapisiPoruku.setRows(5);
        jScrollPane1.setViewportView(txtNapisiPoruku);

        porukaPrivatna.setText("privatno");
        porukaPrivatna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porukaPrivatnaActionPerformed(evt);
            }
        });

        jLabel3.setText("tvoje poruke:");

        txtTvojePoruke.setColumns(20);
        txtTvojePoruke.setRows(5);
        jScrollPane2.setViewportView(txtTvojePoruke);

        porukaSvima.setText("svima");
        porukaSvima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porukaSvimaActionPerformed(evt);
            }
        });

        jLabel4.setText("posalji poruku");

        tblPoslednjeTri.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblPoslednjeTri);

        tblSveOstale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tblSveOstale);

        jLabel5.setText("poslednje 3:");

        jLabel6.setText("sve ostale");

        btnCelaPoruka.setText("vidi celu poruku");
        btnCelaPoruka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCelaPorukaActionPerformed(evt);
            }
        });

        jButton2.setText("vidi celu poruku");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(txtDobrodoslica, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(cmbKorisnici, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(19, 19, 19)
                                            .addComponent(porukaSvima)
                                            .addGap(31, 31, 31)
                                            .addComponent(porukaPrivatna))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCelaPoruka))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtDobrodoslica)
                .addGap(9, 9, 9)
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbKorisnici, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(porukaPrivatna)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(porukaSvima)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnCelaPoruka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //dugme za odjavu
        //salje se zahtev sa IDjem korisnika
        Komunikacija.getInstance().posaljiLogout(k.getKorisnikID());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void porukaSvimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porukaSvimaActionPerformed
        String tekst = txtNapisiPoruku.getText();
        if (tekst.length() > 200) {
            JOptionPane.showMessageDialog(this, "poruka je predugacka");
            return;
        }
        Korisnik odKoga = k;
        
        Date sada = new Date();
        //long sad = System.currentTimeMillis();
        
        Poruka p = new Poruka(-1, odKoga, null, tekst, sada);
        Komunikacija.getInstance().posaljiPoruku(p);
        txtNapisiPoruku.setText("");
    }//GEN-LAST:event_porukaSvimaActionPerformed

    private void porukaPrivatnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porukaPrivatnaActionPerformed
        String tekst = txtNapisiPoruku.getText();
        if (tekst.length() > 200) {
            JOptionPane.showMessageDialog(this, "poruka je predugacka");
            return;
        }
        Korisnik odKoga = k;
        Korisnik zaKoga = (Korisnik) cmbKorisnici.getSelectedItem();
        
        Date sada = new Date();
        
        Poruka p = new Poruka(-1, odKoga, zaKoga, tekst, sada);
        Komunikacija.getInstance().posaljiPoruku(p);
        txtNapisiPoruku.setText("");
    }//GEN-LAST:event_porukaPrivatnaActionPerformed

    private void btnCelaPorukaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCelaPorukaActionPerformed
        ModelTabeleKlijent mtkPoslednjeTri = (ModelTabeleKlijent) tblPoslednjeTri.getModel();
        int rowPrveTri = tblPoslednjeTri.getSelectedRow();
        Poruka p = mtkPoslednjeTri.getListaPoruka().get(rowPrveTri);
        JOptionPane.showMessageDialog(this, p.getTekst());
    }//GEN-LAST:event_btnCelaPorukaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ModelTabeleKlijent mtkSveOstale = (ModelTabeleKlijent) tblSveOstale.getModel();
        int rowOstale = tblSveOstale.getSelectedRow();
        Poruka p = mtkSveOstale.getListaPoruka().get(rowOstale);
        JOptionPane.showMessageDialog(this, p.getTekst());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCelaPoruka;
    private javax.swing.JComboBox cmbKorisnici;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton porukaPrivatna;
    private javax.swing.JButton porukaSvima;
    private javax.swing.JTable tblPoslednjeTri;
    private javax.swing.JTable tblSveOstale;
    private javax.swing.JLabel txtDobrodoslica;
    private javax.swing.JTextArea txtNapisiPoruku;
    private javax.swing.JTextArea txtTvojePoruke;
    // End of variables declaration//GEN-END:variables

    public void obradiLogout(boolean uspesno) {
        if (uspesno ){
            JOptionPane.showMessageDialog(this, "uspesno ste se odjavili");
            this.dispose();
        } else JOptionPane.showMessageDialog(this, "sorru");
    }

    public void obradiUgasenServer(String poruka) {
        JOptionPane.showMessageDialog(this, poruka);
        this.dispose();
    }

    void popuniKombo() {
        Komunikacija.getInstance().posaljiZahtevZaKomboAktivneKorisnike();
    }

    public void obradiListuPopuniKombo(ArrayList<Korisnik> listaUlogovanihKorisnika) {
        cmbKorisnici.removeAllItems();
        //cmbKorisnici.addItem("svima");
        for (Korisnik korisnik : listaUlogovanihKorisnika) {
            if (korisnik.getKorisnikID() == k.getKorisnikID()) continue;
            cmbKorisnici.addItem(korisnik);
        }
    }

    public void obradiPrikaziPoruku(Poruka p) {
        //imamo vise slucaja
        //zelim da kad je odKoga = ja da pise ja: pa poruka
        //treba da se odradi kontatizacija stringova
        //kad je zaKoga = null da pise obicno nova poruka od blabla
        //a kad nije null da pise PRIVATNA PORUKA OD blabla
        String dosadasnjePoruke = "";
        dosadasnjePoruke = txtTvojePoruke.getText();
        String novaPoruka;
        
        if (p.getOdKoga().getKorisnikID() == k.getKorisnikID() && p.getZaKoga() != null) {
            novaPoruka = "Ja za " + p.getZaKoga() + ":" + p.getTekst() + "\n";
        } else if (p.getOdKoga().getKorisnikID() == k.getKorisnikID() && p.getZaKoga() == null) {
            novaPoruka = "Ja: " + p.getTekst() + "\n";
        } else if (p.getOdKoga().getKorisnikID() != k.getKorisnikID() && p.getZaKoga() != null) {
            novaPoruka = "PRIVATNA poruka od " + p.getOdKoga().getUsername() + ":" + p.getTekst() + "\n";
        } else  novaPoruka = "Poruka od " + p.getOdKoga().getUsername() + ":" + p.getTekst() + "\n"; 
        
        
        String svePoruke = dosadasnjePoruke + novaPoruka;
        txtTvojePoruke.setText(svePoruke);
        
        popuniTabeluPorukom(p);
    }

    private void popuniTabeluPorukom(Poruka p) {
        ModelTabeleKlijent mtkPoslednjeTri = (ModelTabeleKlijent) tblPoslednjeTri.getModel();
        if (mtkPoslednjeTri.getListaPoruka().size() <= 2) {
            mtkPoslednjeTri.dodajPoruku(p);
        } else {
            Poruka prva = mtkPoslednjeTri.dajPrvu();
            ModelTabeleKlijent mtk1 = (ModelTabeleKlijent) tblSveOstale.getModel();
            mtkPoslednjeTri.dodajPoruku(p);
            mtk1.dodajPoruku(prva);
            mtkPoslednjeTri.getListaPoruka().remove(0);
            mtkPoslednjeTri.fireTableDataChanged();
        }
        
        
    }

    
}
